#!/bin/sh

# Script to communicate from linux receivers to ambi-tv on Raspi via socket
# Plugins shellexec and msgbox are necessary
# make this entry in shellexecs menufile 'ACTION=&Ambilight-Steuerung,/var/plugins/ambi-tv-config [IP-and-port-of-raspi]'
# Copyright (C) 2015 by SnowHead

# configure IP and socket port of RASPI here if not done by call
[ -z "$1" ] && RASPI=192.168.0.114:16384 || RASPI="$1"

SMOOTH_FALLOFF=1
SMOOTH_AVERAGE=2
SMOOTH_INTEGRAL=4

MENUFILE="/tmp/ambilight.mnu"
TEMPFILE="/tmp/ambilight.tmp"
STATFILE="/tmp/.ambistate"
SMOOTHFILE="/tmp/.ambismooth_"
LINEARFILE="/tmp/.ambilinear"

dogamma=""
dointensity=""

case "$2" in
"asensitivity")
	[ -e $STATFILE ] && sensitivity=`grep sensitivity $STATFILE | cut -d'=' -f2` || sensitivity=100
	sensitivity=`input l="###" t="Empfindlichkeit" d=$sensitivity`;
	if [ $sensitivity -ge 0 -a $sensitivity -le 1000 ]
	then
		wget -q -Y off -O /dev/null "http://$RASPI?sensitivity=$sensitivity"
		sed -i s/"sensitivity=.*$"/"sensitivity=$sensitivity"/ $STATFILE
	fi
;;

"asmoothing")
	parm=$3
	if pval=`grep smoothing $STATFILE`
	then
		smoothing=`echo $pval | cut -d'=' -f2`
		smoothing=$(($smoothing^$parm))
		[ $(($smoothing&$parm)) -gt 0 ] && touch $SMOOTHFILE$parm || rm -f $SMOOTHFILE$parm
		sed -i s/"smoothing=.*$"/"smoothing=$smoothing"/ $STATFILE
		wget -q -Y off -O /dev/null "http://$RASPI?smoothing=$smoothing"
	fi
;;

"alinear")
	if pval=`grep linear $STATFILE`
	then
		linear=`echo $pval | cut -d'=' -f2`
		linear=$(($linear^1))
		[ $linear -gt 0 ] && touch $LINEARFILE || rm -f $LINEARFILE
		sed -i s/"linear=.*$"/"linear=$linear"/ $STATFILE
		wget -q -Y off -O /dev/null "http://$RASPI?linear=$linear"
	fi
;;

"bright")
	[ -e $STATFILE ] && brightness=`grep brightness $STATFILE | cut -d'=' -f2` || brightness=100
	brightness=`input l="###%" t="Helligkeit" d=$brightness`;
	if [ $brightness -ge 0 -a $brightness -le 100 ]
	then
		wget -q -Y off -O /dev/null "http://$RASPI?brightness=$brightness"
		sed -i s/"brightness=.*$"/"brightness=$brightness"/ $STATFILE
	fi
;;

"ired")
	dointensity=`expr substr $1 2 10`
;;

"igreen")
	dointensity=`expr substr $1 2 10`
;;

"iblue")
	dointensity=`expr substr $1 2 10`
;;

"gred")
	dogamma=`expr substr $1 2 10`
;;

"ggreen")
	dogamma=`expr substr $1 2 10`
;;

"gblue")
	dogamma=`expr substr $1 2 10`
;;

*)
	program=0

	wget -q -O- http://$RASPI?getconfig | sed -e s/'<br>'//g -e s/"\t"/' '/g -e s/'  '*/' '/g > $TEMPFILE
	if ! grep program $TEMPFILE > /dev/null
	then
		msgbox title="Ambilight-Steuerung" msg="~RFehler!~S Raspberry antwortet nicht" 
		exit 0 
	fi

	if [ ! -e $STATFILE ]
	then
		parpos=1
		for param in "smoothing" "sensitivity" "linear" "brightness" "intensity-red" "intensity-green" "intensity-blue" "gamma-red" "gamma-green" "gamma-blue"
		do
			pval=`grep "$param" $TEMPFILE | cut -d' ' -f3 | sed -e s/'\.'//`
			pval=`echo $pval | sed s/' .*$'//g`
			if [ $parpos -ge 8 ]
			then
				pval=$pval"00"
				pval=`expr substr $pval 1 3`
			fi
			echo $param=$pval >> $STATFILE
			parpos=$(($parpos+1))
		done
	fi
	if pval=`grep smoothing $STATFILE`
	then
		hasaudio=3
		smoothing=`echo $pval | cut -d'=' -f2`
		for i in $SMOOTH_FALLOFF $SMOOTH_AVERAGE $SMOOTH_INTEGRAL
		do
			[ $(($smoothing&$i)) -gt 0 ] && touch $SMOOTHFILE$i || rm -f $SMOOTHFILE$i
		done
	else
		hasaudio=0
		smoothing=0
	fi

	echo WIDTH=440 > $MENUFILE
	echo HIGHT=500 >> $MENUFILE
	echo LINESPP=$((11+$hasaudio)) >> $MENUFILE
	echo FONTSIZE=24 >> $MENUFILE
	echo MENU=Ambilight-Steuerung >> $MENUFILE
	echo COMMENT=!Ambilight-Modus >> $MENUFILE
	cat $TEMPFILE | grep ^\& | sed s/^\&// | while read line
	do
		if echo $line | grep '#' > /dev/null
		then
			title=`echo $line | cut -d'#' -f2`
		else
			title=`echo $line | cut -d' ' -f1 | sed s/program_//`
		fi
		echo ACTION=\&"$title",wget -q -Y off -O /dev/null "http://$RASPI?mode=$program" >> $MENUFILE
		program=$(($program+1))
	done
	echo ACTION=\&Ausschalten,wget -q -Y off -O /dev/null "http://$RASPI?mode=X" >> $MENUFILE
	echo COMMENT=!Ambilight-Parameter >> $MENUFILE
	echo ACTION=\&"Helligkeit einstellen","$0 $RASPI bright" >> $MENUFILE
	echo MENU=Farbeinstellungen >> $MENUFILE
	echo ACTION=\&"Intensit~at Rot","$0 $RASPI ired" >> $MENUFILE
	echo ACTION=\&"Intensit~at Gr~un","$0 $RASPI igreen" >> $MENUFILE
	echo ACTION=\&"Intensit~at Blau","$0 $RASPI iblue" >> $MENUFILE
	echo COMMENT=! >> $MENUFILE
	echo ACTION=\&"Gammawert Rot","$0 $RASPI gred" >> $MENUFILE
	echo ACTION=\&"Gammawert Gr~un","$0 $RASPI ggreen" >> $MENUFILE
	echo ACTION=\&"Gammawert Blau","$0 $RASPI gblue" >> $MENUFILE
	echo ENDMENU >> $MENUFILE
	if [ $hasaudio -gt 0 ]
	then
		echo MENU=Audioeinstellungen >> $MENUFILE
		echo ACTION=\&"Empfindlichkeit","$0 $RASPI asensitivity" >> $MENUFILE
		echo MENU=Smoothing >> $MENUFILE
			echo DEPENDON=\&"Falloff~t~t~t~t~t~tein","$0 $RASPI asmoothing $SMOOTH_FALLOFF","$SMOOTHFILE"1 >> $MENUFILE
			echo DEPENDOFF=\&"Falloff~t~t~t~t~t~taus","$0 $RASPI asmoothing $SMOOTH_FALLOFF","$SMOOTHFILE"1 >> $MENUFILE
			echo DEPENDON=\&"Average~t~t~t~t~t~tein","$0 $RASPI asmoothing $SMOOTH_AVERAGE","$SMOOTHFILE"2 >> $MENUFILE
			echo DEPENDOFF=\&"Average~t~t~t~t~t~taus","$0 $RASPI asmoothing $SMOOTH_AVERAGE","$SMOOTHFILE"2 >> $MENUFILE
			echo DEPENDON=\&"Integral~t~t~t~t~t~tein","$0 $RASPI asmoothing $SMOOTH_INTEGRAL","$SMOOTHFILE"4 >> $MENUFILE
			echo DEPENDOFF=\&"Integral~t~t~t~t~t~taus","$0 $RASPI asmoothing $SMOOTH_INTEGRAL","$SMOOTHFILE"4 >> $MENUFILE
		echo ENDMENU >> $MENUFILE
		echo DEPENDON=\&"Linear~t~t~t~t~t~tein","$0 $RASPI alinear","$LINEARFILE" >> $MENUFILE
		echo DEPENDOFF=\&"Linear~t~t~t~t~t~taus","$0 $RASPI alinear","$LINEARFILE" >> $MENUFILE
		echo ENDMENU >> $MENUFILE
	fi 
	echo ENDMENU >> $MENUFILE
	rm $TEMPFILE
	shellexec $MENUFILE
	rm $MENUFILE
;;
esac

if [ ! -z $dogamma ]
then
	[ -e $STATFILE ] && gval=`grep "gamma-$dogamma" $STATFILE | cut -d'=' -f2` || gval=1.5
	gval=`input l=#.## t="Gammawert" d=$gval`;
	if [ $gval -ge 000 -a $gval -le 999 ]
	then
		gfval=`expr substr $gval 1 1`.`expr substr $gval 2 2`
		wget -q -Y off -O /dev/null "http://$RASPI?gamma-$dogamma=$gfval"
		sed -i /"gamma-$dogamma"/d $STATFILE
		echo "gamma-$dogamma=$gval" >> $STATFILE
	fi
fi

if [ ! -z $dointensity ]
then
	[ -e $STATFILE ] && ival=`grep "intensity-$dointensity" $STATFILE | cut -d'=' -f2` || ival=100
	ival=`input l="###%" t="Intensit~at" d=$ival`;
	if [ $ival -ge 0 -a $ival -le 100 ]
	then
		wget -q -Y off -O /dev/null "http://$RASPI?intensity-$dointensity=$ival"
		sed -i /"intensity-$dointensity"/d $STATFILE
		echo "intensity-$dointensity=$ival" >> $STATFILE
	fi
fi

exit 0