#!/bin/sh
# Emacs settings: -*- tab-width: 4 -*-
#
# Copyright (c) 2002-2006 Apple Computer, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Linux /etc/init.d script to start/stop the mdnsd daemon.
#
# The following lines are used by the *BSD rcorder system to decide
# the order it's going to run the rc.d scripts at startup time.
# PROVIDE: ambi-tv 
# REQUIRE: 

### BEGIN INIT INFO
# Provides:        ambi-tv 
# Required-Start:  
# Required-Stop:   
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: ambi-tv 
### END INIT INFO

NAME="ambi-tv daemon"
DAEMON=/usr/bin/ambi-tv
OPTS="-f /etc/ambi-tv.conf"

test -r $DAEMON || exit 0

# Some systems have start-stop-daemon, some don't. 
if [ -r /sbin/start-stop-daemon ]; then
	start() {
            start-stop-daemon --start --background --quiet --make-pidfile --pidfile /var/run/ambi-tv.pid --startas /bin/bash -- -c "exec $DAEMON $OPTS >/dev/null 2>&1" 
        }
        START=start	
        # Suse Linux doesn't work with symbolic signal names, but we really don't need
	# to specify "-s TERM" since SIGTERM (15) is the default stop signal anway
	# STOP="start-stop-daemon --stop -s TERM --quiet --oknodo --exec"
	STOP="start-stop-daemon --stop --quiet --remove-pidfile --pidfile /var/run/ambi-tv.pid --oknodo"
else
        startambitv() {
                $DAEMON $OPTS 1> /dev/null 2>&1 &
                echo $! > /var/run/ambi-tv.pid 
        }
	killambitv() {
		kill -TERM `cat /var/run/ambi-tv.pid`
	}
	START=
	STOP=killambitv
fi

case "$1" in
    start)
	echo -n "Starting $NAME:"
	echo -n " ambi-tv"
        $START 
	echo "."
	;;
    stop)
        echo -n "Stopping $NAME:"
        echo -n " ambi-tv" ; $STOP $DAEMON
        echo "."
	;;
    reload|restart|force-reload)
		echo -n "Restarting $NAME:"
		$STOP $DAEMON
		sleep 1
		$START $DAEMON
		echo -n " ambi-tv"
	;;
    *)
	echo "Usage: /etc/init.d/ambi-tv {start|stop|reload|restart}"
	exit 1
	;;
esac

exit 0
